Repository RevenueCat/cordova-plugin-purchases, pull requests merged in 2022-08, with the labels that each got.

#176 Configures danger
  .circleci/config.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: ci

#177 Add support for Firebase, Mixpanel, and CleverTap integrations
  CHANGELOG.md
  VERSIONS.md
  apiTester/attributes.ts
  plugin.xml
  src/android/PurchasesPlugin.java
  src/ios/PurchasesPlugin+Attribution.swift
  src/plugin/plugin.ts
  www/plugin.d.ts
  www/plugin.js
Labels: feat

#178 Preparing for version 3.0.0-rc.8
  CHANGELOG.md
  package.json
  plugin.xml
  scripts/docs/index.html
  src/android/PurchasesPlugin.java
  src/ios/PurchasesPlugin.swift
Labels: next_release

#180 Increase timeout for pod command
  .circleci/config.yml
Labels: build
