Repository RevenueCat/cordova-plugin-purchases, pull requests merged in 2022-09, with the labels that each got.

#183 fix: race conditions in example app
  examples/cordova-sample/MyApp/www/js/index.js
Labels: ci

#179 add SDK reference docs link
  README.md
Labels: docs

#182 Automate releases using the fastlane plugin
  .circleci/config.yml
  .gitignore
  .npmignore
  .npmrc.SAMPLE
  .version
  CHANGELOG.latest.md
  Gemfile
  Gemfile.lock
  RELEASING.md
  fastlane/.env.SAMPLE
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/README.md
Labels: ci

#189 Fix prepare_next_version job in CircleCI machines
  Gemfile.lock
Labels: ci

#193 Configure should be called in the current thread and not in a UI thread
  examples/cordova-sample/MyApp/www/js/index.js
  src/android/PurchasesPlugin.java
Labels: fix

#186 Improve purchase tester
  examples/cordova-sample/MyApp/www/css/index.css
  examples/cordova-sample/MyApp/www/index.html
  examples/cordova-sample/MyApp/www/js/index.js
Labels: test

#194 Updates from 2.4.1 to main
  CHANGELOG.md
  VERSIONS.md
  package.json
Labels: next_release

#196 Removes PurchasesPromotionalOffer
  apiTester/offerings.ts
  apiTester/purchases.ts
  src/plugin/plugin.ts
  www/plugin.d.ts
Labels: fix
