Repository RevenueCat/cordova-plugin-purchases, pull requests merged in 2022-11, with the labels that each got.

#212 Update fastlane-plugin-revenuecat_internal
  Gemfile.lock
Labels: ci

#214 Adds missing parameter to bump_version_update_changelog_create_pr
  fastlane/Fastfile
Labels: ci

#215 Makes hold job depend on integration tests
  .circleci/config.yml
Labels: ci

#188 Untangle configure and delegate
  examples/cordova-sample/MyApp/www/css/index.css
  examples/cordova-sample/MyApp/www/js/index.js
  src/android/PurchasesPlugin.java
  src/ios/PurchasesPlugin.swift
  src/plugin/plugin.ts
  tests/plugin.test.ts
  www/plugin.js
Labels: fix

#218 Update Fastlane plugin
  Gemfile.lock
Labels: ci

#221 Bring 2.4.2 changes to main (Setting type of module to `commonjs`)
  CHANGELOG.md
  VERSIONS.md
  package.json
Labels: build

#226 Fix CDVPlugin class CDVPurchasesPlugin (pluginName: purchasesplugin) does not exist bug
  src/ios/PurchasesPlugin.swift
Labels: fix
