Repository RevenueCat/cordova-plugin-purchases, pull requests merged in 2023-01, with the labels that each got.

#252 remove stalebot in favor of SLAs in Zendesk
  .github/stale.yml
Labels: ci

#255 Update Gemfile.lock
  Gemfile.lock
Labels: ci

#256 Adds missing params for better changelogs when bumping
  Gemfile.lock
  fastlane/Fastfile
Labels: ci

#260 Update Gemfile.lock
  Gemfile.lock
Labels: ci

#264 Adds PurchasesStoreProduct.subscriptionPeriod
  apiTester/offerings.ts
  src/plugin/plugin.ts
  www/plugin.d.ts
Labels: feat

#269 Ignores www folder and build on prepare
  .circleci/config.yml
  .gitignore
  .npmignore
  package.json
  www/plugin.d.ts
  www/plugin.js
Labels: build

#265 Add usesStoreKit2IfAvailable to PurchasesConfiguration
  src/android/PurchasesPlugin.java
  src/ios/PurchasesPlugin.swift
  src/plugin/plugin.ts
  tests/plugin.test.ts
Labels: feat

#270 Added `Purchases.setLogLevel`
  apiTester/purchases.ts
  src/android/PurchasesPlugin.java
  src/ios/PurchasesPlugin.swift
  src/plugin/plugin.ts
Labels: feat

#276 Update gems
  Gemfile.lock
Labels: dependencies
