Repository RevenueCat/cordova-plugin-purchases, pull requests merged in 2023-02, with the labels that each got.

#277 Configures dependabot
  .github/dependabot.yml
  Gemfile
Labels: ci

#279 Remove req of macOS to avoid confusion
  README.md
Labels: docs

#275 setLogHandler support
  apiTester/purchases.ts
  src/android/PurchasesPlugin.java
  src/ios/PurchasesPlugin.swift
  src/plugin/plugin.ts
  tests/plugin.test.ts
Labels: feat

#284 Fix Android integration tests
  .circleci/config.yml
Labels: ci

#289 Formats files correctly
  .editorconfig
  src/android/PurchasesPlugin.java
  src/plugin/plugin.ts
Labels: style

#288 Add `syncObserverModeAmazonPurchase`
  apiTester/purchases.ts
  src/android/PurchasesPlugin.java
  src/ios/PurchasesPlugin+Purchasing.swift
  src/plugin/plugin.ts
  tests/plugin.test.ts
Labels: feat

#298 Fix `canMakePayments` jsdoc
  src/plugin/plugin.ts
Labels: docs
