Repository RevenueCat/cordova-plugin-purchases, pull requests merged in 2023-11, with the labels that each got.

#446 release/2.4.3
  .circleci/config.yml
  CHANGELOG.md
  VERSIONS.md
  package.json
  plugin.xml
  src/android/PurchasesPlugin.java
  src/ios/CDVPurchasesPlugin.m
Labels: next_release

#447 Add `2.4.3` to `VERSIONS`
  VERSIONS.md
Labels: docs

#454 `CI`: disable `prepare-next-version`
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#460 Fix some docs
  README.md
  src/plugin/plugin.ts
Labels: docs
