Repository RevenueCat/cordova-plugin-purchases, pull requests merged in 2023-06, with the labels that each got.

#355 Add metadata to offering
  apiTester/offerings.ts
  examples/cordova-sample/MyApp/www/js/index.js
  plugin.xml
  src/plugin/plugin.ts
Labels: feat

#356 Release/4.0.0-rc.1
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  package.json
  plugin.xml
  scripts/docs/index.html
  src/android/PurchasesPlugin.java
  src/ios/PurchasesPlugin.swift
Labels: next_release

#360 Update PHC to 5.0.0
  plugin.xml
Labels: breaking, build

#361 Release/4.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  package.json
  plugin.xml
  scripts/docs/index.html
  src/android/PurchasesPlugin.java
  src/ios/PurchasesPlugin.swift
Labels: next_release

#363 Remove api key
  examples/cordova-sample/MyApp/www/js/index.js
Labels: fix
