Repository RevenueCat/cordova-plugin-purchases, pull requests merged in 2023-10, with the labels that each got.

#425 Temporarily remode DEFERRED proration mode in preparation for upgrade to Billing Client 6
  apiTester/enums.ts
  src/plugin/plugin.ts
Labels: breaking

#430 Add in app message apis
  apiTester/enums.ts
  apiTester/purchases.ts
  examples/cordova-sample/MyApp/www/index.html
  examples/cordova-sample/MyApp/www/js/index.js
  src/android/PurchasesPlugin.java
  src/ios/PurchasesPlugin+Purchasing.swift
  src/ios/PurchasesPlugin.swift
  src/plugin/plugin.ts
  tests/plugin.test.ts
Labels: feat

#431 Release/5.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  VERSIONS.md
  package.json
  plugin.xml
  scripts/docs/index.html
  src/android/PurchasesPlugin.java
  src/ios/PurchasesPlugin.swift
Labels: next_release
